### PR TITLE
Better bdb

### PR DESCRIPTION
**Pull request by UnixJunkie**
allow people to use the Bdb module directly

### CODE REVIEW

**Comment by UnixJunkie** [comment]
I need those for this:
https://github.com/UnixJunkie/dokeysto/issues/22

**Comment by UnixJunkie** [comment]
@toolslive Hi, what do you think about this PR?
Note that I also added a test script to test Bdb can be used in a standalone way.

**Comment by UnixJunkie** [comment]
Thanks! Can you issue a new tag so that I can update the opam package?

**Comment by toolslive** [comment]
tagged.

**Pull request merged**
