### PR TITLE
Camltci ocamldoc

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by UnixJunkie** [comment]
note that I put DOCUMENT_ME when I have no idea of the underlying behavior but would like to know it

**Comment by UnixJunkie** [comment]
that's quite safe to merge, you just need to fill in the DOCUMENT_ME bits

**Comment by UnixJunkie** [comment]
You can also close this PR it if it is never going to be accepted.
Or let me know what I could do to make it being accepted.

**Comment by andersfugmann** [comment]
Documentation improvements should always be welcome, however the PR has conflicts. 

I will create a PR for generating gitgub pages with dune generated documentation.

**Comment by UnixJunkie** [comment]
superseded by https://github.com/toolslive/camltc/pull/48

**Pull request closed without merging**
